### ISSUE TITLE
Quantity below 1

### ISSUE THREAD

**Issue by sapooh** [msylvestre/couponapp#33]
J'ai testé la quantité d'un item avec la valeur 0.5 (possible d'acheter juste 1/2lbs de viande, mettons)  et la quantité n'affiche pas dans la liste.  Je sais que tu n'as pas fini de travailler sur ça, mais bon, c'est flaggé.

![betsy - quantity issue](https://cloud.githubusercontent.com/assets/10343013/5605335/df8e1914-93c2-11e4-92a4-e675be729d16.png)

**Comment by msylvestre** [comment]
ah ouais, dans qty, c'est des nombre entier seulement.  Je vais changer
pour un double-digit, pour pouvoir faire 1/4 --> 0.25

*/Marco*
Co-Founder




2015-01-04 3:36 GMT-05:00 Sab <notifications@github.com>:

**Comment by sapooh** [comment]
Peux-tu en mettre 3 après la virgule, pour les viandes, c'est x,xxxkg

**Comment by msylvestre** [comment]
fixed.  min = 0.001.  increment par 0.001

**Comment by sapooh** [comment]
ça marche tiguidoo !
